### ISSUE TITLE
[Issue] Crash when opening BL menu in Freeroam

### ISSUE THREAD

**Issue by DiamondMaster07** [ExOptsTeam/NFSMWExOpts#20] opened 2017-08-22 17:40 UTC
When I launch the game and instantly go to free roam, the game often crashes when I try to open the Blacklist menu. When I open the BL menu in the Career menu, it opens normally. I don't know what causing this.

**Comment by berkay2578** [comment] 2017-08-22 17:55
Works fine here. Can you post your ini and also list any other plugins that you are using?

**Comment by DiamondMaster07** [comment] 2017-08-22 18:01
Here are my .ini files(renamed to .txt)
[NFSMostWanted.WidescreenFix.txt](https://github.com/nlgzrgn/NFSMWExOpts/files/1242908/NFSMostWanted.WidescreenFix.txt)
[NFSMWExtraOptionsSettings.txt](https://github.com/nlgzrgn/NFSMWExOpts/files/1242906/NFSMWExtraOptionsSettings.txt)
[NFSMWGraphicsSettings.txt](https://github.com/nlgzrgn/NFSMWExOpts/files/1242907/NFSMWGraphicsSettings.txt)

**Comment by berkay2578** [comment] 2017-08-22 18:09
Looks fine. Are you sure you didn't set any of the hotkeys to your in-game Open Blacklist key? All I can think of right now is `ReplayBlacklistRaces` being enabled might cause such an issue but I can't reproduce here.

**Comment by DiamondMaster07** [comment] 2017-08-22 18:12
Thx, found out the problem was with ReplayBlacklistRaces enabled.

**Comment by berkay2578** [comment] 2017-08-22 18:22
@nlgzrgn `ReplayBlacklistRaces` seems to cause a crash. I can reproduce with a 100% save.

**Comment by nlgzrgn** [comment] 2018-03-30 14:16
A fix for this is added in v7.0.1.1337.

**Closed by nlgzrgn** 2018-03-30 14:16 UTC
